### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by publicocean0** [NetoDevel/cli-spring-boot-scaffold#39]
cristian@fenix:~/temp/spring-react-boilerplate$ spring scaffold -n "User" -p "name:String email:String username:String password:String enabled:Boolean locked:Boolean " 
create src/main/java/com/example/model/UserModel.java
create src/main/java/com/example/repository/UserRepository.java
create src/main/java/com/example/service/UserService.java
create src/main/java/com/example/controller/UserController.java
create /src/main/resources/templates/user/index.html
create /src/main/resources/templates/user/form.html
create /src/main/resources/templates/user/show.html
java.lang.Exception: type not implemented
	at br.com.generate.migrate.GenerateMigration.convertTypeJavaToSQLType(GenerateMigration.java:55)
	at br.com.generate.migrate.GenerateMigration.createMigrationFromModel(GenerateMigration.java:23)
	at br.com.generate.migrate.Migrations.create(Migrations.java:10)
	at br.com.netodevel.scaffold.ScaffoldHandler.generateScaffoldJava(ScaffoldHandler.java:58)
	at br.com.netodevel.scaffold.ScaffoldHandler.generateJava(ScaffoldHandler.java:48)
	at br.com.netodevel.scaffold.ScaffoldHandler.run(ScaffoldHandler.java:43)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:84)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by publicocean0** [comment]
Boolean , boolean type not handled

**Comment by NetoDevel** [comment]
@publicocean0 I'll replicate the scenario here and fix.

**Comment by publicocean0** [comment]
ok thanks , pay attention to getter definition in pojo ...

**Comment by publicocean0** [comment]
same problem with type double
